-------------------------------------------------------------------------------
-- 特定のシステムアカウントが指定日時点で有する権限を取得する
-------------------------------------------------------------------------------
SEARCH_AUTHORIZED_REQUEST =
SELECT
    R.REQUEST_ID,
    R.REQUEST_NAME
FROM
    REQUEST R 
      INNER JOIN PERMISSION_UNIT_REQUEST PUR ON R.REQUEST_ID = PUR.REQUEST_ID
      INNER JOIN PERMISSION_UNIT PU          ON PUR.PERMISSION_UNIT_ID = PU.PERMISSION_UNIT_ID
      INNER JOIN UGROUP_AUTHORITY UA         ON PU.PERMISSION_UNIT_ID = UA.PERMISSION_UNIT_ID
      INNER JOIN UGROUP U                    ON UA.UGROUP_ID = U.UGROUP_ID
      INNER JOIN UGROUP_SYSTEM_ACCOUNT USA   ON U.UGROUP_ID = USA.UGROUP_ID
      INNER JOIN SYSTEM_ACCOUNT SA           ON USA.USER_ID = SA.USER_ID
WHERE
    SA.USER_ID = ?
    AND ? BETWEEN USA.EFFECTIVE_DATE_FROM AND USA.EFFECTIVE_DATE_TO
    AND ? BETWEEN SA.EFFECTIVE_DATE_FROM AND SA.EFFECTIVE_DATE_TO
    