title = "Santoku"
description = ""
hasCJKLanguage = true

theme = "book"

relativeURLs = true
# GitLabのJob artifactを確認する場合、ディレクトリアクセスだとindex.htmlを表示してくれない
# uglyurls = trueにすれば解消されるが、そうするとマークダウン中の画像パス指定がそれに合わせる必要があり
# GitLabまたはGitHubでリポジトリを見た時に、またはローカル開発時にマークダウンプレビューで画像で表示されない
# 以上のことからGitLabのJob artifactでの問題は目をつぶり、それ以外での扱いやすさを優先するため
# ここではuglyurls = falseを設定する
uglyurls = false

enableEmoji = true

[markup.goldmark.renderer]
# Markdownファイル内でHTMLタグを有効にする
unsafe = true

[params]
# 使用テーマは左メニューエリアに検索窓があるが
# 本ドキュメントはページ数が少ないため
# 検索機能は不要と判断し無効にする
BookSearch = false
