title = "Santoku"
description = ""
hasCJKLanguage = true
baseURL = "fintan-contents-draft/mobile-app-crib-notes/"

theme = "book"

enableEmoji = true

[markup.goldmark.renderer]
# Markdownファイル内でHTMLタグを有効にする
unsafe = true
