title = "Santoku"
description = ""
hasCJKLanguage = true

theme = "book"

baseURL = "fintan-contents-draft/mobile-app-crib-notes"
canonifyURLs = true
relativeURLs = true
# GitLabのJob artifactを確認する場合、ディレクトリアクセスだとindex.htmlを表示してくれない。
# 仕方ないのでURLにディレクトリを使うのではなく、HTMLファイル名を使うようにしておく。
# ただ、左上のロゴからホームへのリンクは `./index.html` ではなく `./` となってしまうので
# Job artifactで確認している時は404となってしまう。
# GitLab Pagesで表示している時は問題ない。
uglyurls = true

enableEmoji = true

[markup.goldmark.renderer]
# Markdownファイル内でHTMLタグを有効にする
unsafe = true
