/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */

export type AccountLoginResponseStatus = typeof AccountLoginResponseStatus[keyof typeof AccountLoginResponseStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountLoginResponseStatus = {
  COMPLETE: 'COMPLETE',
} as const;
