/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */

/**
 * 回答内容
 */
export interface AnswerContent {
  /** 回答ID */
  readonly answerId: string;
  /** 回答内容 */
  content: string;
  /** 回答日時 */
  datetime: string;
  /** いいね数 */
  likes: number;
  /** コメント数 */
  comments: number;
}
