/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */

/**
 * 登録する回答情報
 */
export interface AnswerRegistration {
  /** 回答内容 */
  content: string;
}
