/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */
import type {AnswerContent} from './answerContent';
import type {AccountProfile} from './accountProfile';

/**
 * 回答
 */
export type Answer = AnswerContent & AccountProfile;
