/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */
import type {CommentContent} from './commentContent';
import type {AccountProfile} from './accountProfile';

/**
 * コメント
 */
export type Comment = CommentContent & AccountProfile;
