/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */
import type {ErrorResponse} from './errorResponse';

/**
 * Conflict
 */
export type ConflictResponse = ErrorResponse;
