/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */
import type {GetEventsTarget} from './getEventsTarget';

export type GetEventsParams = {target: GetEventsTarget};
