/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */

export type GetEventsTarget = typeof GetEventsTarget[keyof typeof GetEventsTarget];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetEventsTarget = {
  active: 'active',
  all: 'all',
} as const;
