/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */
import type {GetEventsTarget} from './getEventsTarget';

export type GetEventsParams = {
  /**
   * 取得対象
   */
  target: GetEventsTarget;
};
