/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */

export type GetListQuestionsSort = typeof GetListQuestionsSort[keyof typeof GetListQuestionsSort];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetListQuestionsSort = {
  like: 'like',
  update: 'update',
} as const;
