/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */
import type {GetListQuestionsSort} from './getListQuestionsSort';
import type {GetListQuestionsFilter} from './getListQuestionsFilter';

export type GetListQuestionsParams = {
  /**
   * 検索文言
   */
  keyword?: string;
  /**
   * ソート順
   */
  sort?: GetListQuestionsSort;
  /**
   * 絞り込み条件
   */
  filter?: GetListQuestionsFilter;
  /**
   * 検索タグ
   */
  tag?: string;
};
