/**
 * Generated by orval v6.9.6 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */

export type GetListQuestionsFilter = typeof GetListQuestionsFilter[keyof typeof GetListQuestionsFilter];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetListQuestionsFilter = {
  unanswered: 'unanswered',
  outstanding: 'outstanding',
} as const;
