/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */
import type {LikesResponseItem} from './likesResponseItem';

/**
 * いいね済のイベントID、質問ID、回答ID、コメントID
 */
export type LikesResponse = LikesResponseItem[];
