/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */
import type {LikedQuestionResponseAnswerItem} from './likedQuestionResponseAnswerItem';

/**
 * いいね済の質問IDと紐づく回答ID、コメントID
 */
export interface LikedQuestionResponse {
  /** 質問ID */
  questionId: string;
  /** 質問にいいね済か */
  liked: boolean;
  /** いいね済の質問コメントID */
  commentId: string[];
  /** いいね済の質問に紐づく回答 */
  answer: LikedQuestionResponseAnswerItem[];
}
