/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */

/**
 * いいね済のイベントID
 */
export interface LikedEventResponse {
  /** いいね済のイベントID */
  eventId?: string;
}
