/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */

/**
 * お知らせ情報
 */
export interface Notification {
  /** お知らせID */
  readonly notificationId: string;
  /** お知らせのタイトル */
  title: string;
  /** 発行日時 */
  datetime: string;
  /** お知らせページのURL */
  contentUrl: string;
}
