/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */

export type ProfileTypeItem = typeof ProfileTypeItem[keyof typeof ProfileTypeItem];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfileTypeItem = {
  partner: 'partner',
  techlead: 'techlead',
  administrator: 'administrator',
} as const;
