/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */
import type {ProfileTypeItem} from './profileTypeItem';

/**
 * プロフィール情報
 */
export interface Profile {
  /** アカウントのニックネーム */
  nickname: string;
  /** アカウントのアバター画像のURL */
  avatarImageUrl?: string;
  /** 該当する場合に付与されるアカウントの種類 */
  type: ProfileTypeItem[];
  /** 今期ポイント数 */
  points: number;
  /** 累積ポイント数 */
  totalPoints: number;
}
