/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */
import type {QuestionContent} from './questionContent';
import type {AccountProfile} from './accountProfile';

/**
 * 質問
 */
export type Question = QuestionContent & AccountProfile;
