/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */
import type {QuestionAndAnswerQuestion} from './questionAndAnswerQuestion';
import type {QuestionAndAnswerAnswerListItem} from './questionAndAnswerAnswerListItem';

/**
 * 質問と回答およびコメント
 */
export interface QuestionAndAnswer {
  /** 質問とコメント */
  question: QuestionAndAnswerQuestion;
  /** 回答とコメントのリスト */
  answerList: QuestionAndAnswerAnswerListItem[];
}
