/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */

/**
 * タグ情報
 */
export interface Tag {
  /** タグID */
  readonly tagId: string;
  /** タグ名 */
  tagName: string;
  /** 設定されている質問数 */
  questions: number;
}
