/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */

/**
 * 利用規約
 */
export interface TermsOfService {
  /** 最新の利用規約のバージョン */
  version: string;
  /** 利用規約のURL */
  url: string;
}
