require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

project 'SantokuApp',
  'Debug' => :debug,
  'DebugAdvanced' => :debug,
  'Release' => :release

target 'SantokuApp' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.87.0' }, configurations: ['Debug', 'DebugAdvanced'])
  post_install do |installer|
    flipper_post_install(installer)
  end
end
