/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */
import {useQuery} from 'react-query';
import type {UseQueryOptions, QueryFunction, UseQueryResult, QueryKey} from 'react-query';
import type {CsrfTokenResponse, AppUpdatesResponse, BadRequestResponse} from '.././model';
import {backendCustomInstance} from '../../utils/customInstance';
import type {ErrorType} from '../../utils/customInstance';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * CSRFトークンを取得します。
 * @summary CSRFトークンの取得
 */
export const getCsrfToken = (signal?: AbortSignal) => {
  return backendCustomInstance<CsrfTokenResponse>({url: `/system/csrf-token`, method: 'get', signal});
};

export const getGetCsrfTokenQueryKey = () => [`/system/csrf-token`];

export type GetCsrfTokenQueryResult = NonNullable<Awaited<ReturnType<typeof getCsrfToken>>>;
export type GetCsrfTokenQueryError = ErrorType<unknown>;

export const useGetCsrfToken = <
  TData = Awaited<ReturnType<typeof getCsrfToken>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getCsrfToken>>, TError, TData>;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCsrfTokenQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCsrfToken>>> = ({signal}) => getCsrfToken(signal);

  const query = useQuery<Awaited<ReturnType<typeof getCsrfToken>>, TError, TData>(
    queryKey,
    queryFn,
    queryOptions,
  ) as UseQueryResult<TData, TError> & {queryKey: QueryKey};

  query.queryKey = queryKey;

  return query;
};

/**
 * 指定されたアプリの種別・バージョン番号に対し、アップデートが必要かどうかの判断結果を返します。

サーバに設定されたバージョン番号と指定されたバージョン番号の比較でアップデートの要否が決定します。
大小比較はセマンティックバージョニングのルールに沿って実施されます。
実際に存在するバージョン番号かどうかは判断結果に影響しません。

次の場合はHTTPステータスコード404（Not Found）を応答します。
- iosまたはandroid以外の種別が指定された場合
- セマンティックバージョンとして認識されないバージョン番号が指定された場合

 * @summary アプリ更新情報の取得
 */
export const getAppUpdates = (type: 'ios' | 'android', version: string, signal?: AbortSignal) => {
  return backendCustomInstance<AppUpdatesResponse>({
    url: `/system/app-updates/${type}/${version}`,
    method: 'get',
    signal,
  });
};

export const getGetAppUpdatesQueryKey = (type: 'ios' | 'android', version: string) => [
  `/system/app-updates/${type}/${version}`,
];

export type GetAppUpdatesQueryResult = NonNullable<Awaited<ReturnType<typeof getAppUpdates>>>;
export type GetAppUpdatesQueryError = ErrorType<BadRequestResponse>;

export const useGetAppUpdates = <
  TData = Awaited<ReturnType<typeof getAppUpdates>>,
  TError = ErrorType<BadRequestResponse>,
>(
  type: 'ios' | 'android',
  version: string,
  options?: {query?: UseQueryOptions<Awaited<ReturnType<typeof getAppUpdates>>, TError, TData>},
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAppUpdatesQueryKey(type, version);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAppUpdates>>> = ({signal}) =>
    getAppUpdates(type, version, signal);

  const query = useQuery<Awaited<ReturnType<typeof getAppUpdates>>, TError, TData>(queryKey, queryFn, {
    enabled: !!(type && version),
    ...queryOptions,
  }) as UseQueryResult<TData, TError> & {queryKey: QueryKey};

  query.queryKey = queryKey;

  return query;
};
