/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * SantokuApp Sandbox REST API
 * SantokuApp Sandbox REST API
 * OpenAPI spec version: 1.0.0
 */

export type ListTodoByCursorParams = {
  /**
 * 取得開始位置
TodoIdを指定し、指定したIdの次のアイテムから取得
 */
  cursor?: number;
  /**
   * 最大取得件数
   */
  limit?: number;
};
