/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * SantokuApp Sandbox REST API
 * SantokuApp Sandbox REST API
 * OpenAPI spec version: 1.0.0
 */

export type ListTodoParams = {
  /**
   * ページ番号
   */
  page?: number;
  /**
   * ページサイズ
   */
  size?: number;
  /**
   * ソート順
   */
  sort?: string;
};
