#!/bin/bash

set -euo pipefail

pushd ios
xcodebuild -alltargets clean
xcrun --kill-cache
xcrun simctl shutdown all
xcrun simctl erase all
popd
rm -rf ~/Library/Caches/com.apple.dt.Xcode/
rm -rf ~/Library/Developer/Xcode/DerivedData
rm -rf ~/Library/Developer/Xcode/iOS\ DeviceSupport/*/Symbols/System/Library/Caches
rm -rf $(getconf DARWIN_USER_CACHE_DIR)/org.llvm.clang/ModuleCache
rm -rf $(getconf DARWIN_USER_CACHE_DIR)//org.llvm.clang.$(whoami)/ModuleCache
pod cache clean --all

pushd android
./gradlew clean cleanBuildCache
./gradlew --stop
popd

watchman watch-del-all
rm -vrf $TMPDIR/react-*
rm -vrf $TMPDIR/metro-*
rm -vrf $TMPDIR/haste-map-metro-*
rm -rf node_modules/
npm cache verify

npm ci
npx pod-install