/**
 * Generated by orval v6.17.0 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */
import {useQuery, useMutation} from '@tanstack/react-query';
import type {
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  QueryKey,
} from '@tanstack/react-query';
import type {
  Question,
  BadRequestResponse,
  GetListQuestionsParams,
  QuestionContent,
  QuestionRegistration,
  QuestionAndAnswer,
  AnswerContent,
  AnswerRegistration,
  CommentContent,
  CommentRegistration,
} from '.././model';
import {backendCustomInstance} from '../../utils/customInstance';
import type {ErrorType} from '../../utils/customInstance';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * 質問の一覧を取得します。検索文言やソート条件を指定すると条件に合った質問のみの一覧を取得します。
 * @summary 質問一覧取得
 */
export const getListQuestions = (params?: GetListQuestionsParams, signal?: AbortSignal) => {
  return backendCustomInstance<Question[]>({url: `/questions`, method: 'get', params, signal});
};

export const getGetListQuestionsQueryKey = (params?: GetListQuestionsParams) =>
  [`/questions`, ...(params ? [params] : [])] as const;

export const getGetListQuestionsQueryOptions = <
  TData = Awaited<ReturnType<typeof getListQuestions>>,
  TError = ErrorType<BadRequestResponse>,
>(
  params?: GetListQuestionsParams,
  options?: {query?: UseQueryOptions<Awaited<ReturnType<typeof getListQuestions>>, TError, TData>},
): UseQueryOptions<Awaited<ReturnType<typeof getListQuestions>>, TError, TData> & {queryKey: QueryKey} => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetListQuestionsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getListQuestions>>> = ({signal}) =>
    getListQuestions(params, signal);

  return {queryKey, queryFn, ...queryOptions};
};

export type GetListQuestionsQueryResult = NonNullable<Awaited<ReturnType<typeof getListQuestions>>>;
export type GetListQuestionsQueryError = ErrorType<BadRequestResponse>;

/**
 * @summary 質問一覧取得
 */
export const useGetListQuestions = <
  TData = Awaited<ReturnType<typeof getListQuestions>>,
  TError = ErrorType<BadRequestResponse>,
>(
  params?: GetListQuestionsParams,
  options?: {query?: UseQueryOptions<Awaited<ReturnType<typeof getListQuestions>>, TError, TData>},
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
  const queryOptions = getGetListQuestionsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {queryKey: QueryKey};

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 質問を登録します。
 * @summary 質問登録
 */
export const postQuestions = (questionRegistration: QuestionRegistration) => {
  return backendCustomInstance<QuestionContent>({
    url: `/questions`,
    method: 'post',
    headers: {'Content-Type': 'application/json'},
    data: questionRegistration,
  });
};

export const getPostQuestionsMutationOptions = <TError = ErrorType<BadRequestResponse>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postQuestions>>,
    TError,
    {data: QuestionRegistration},
    TContext
  >;
}): UseMutationOptions<Awaited<ReturnType<typeof postQuestions>>, TError, {data: QuestionRegistration}, TContext> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postQuestions>>,
    {data: QuestionRegistration}
  > = props => {
    const {data} = props ?? {};

    return postQuestions(data);
  };

  return {mutationFn, ...mutationOptions};
};

export type PostQuestionsMutationResult = NonNullable<Awaited<ReturnType<typeof postQuestions>>>;
export type PostQuestionsMutationBody = QuestionRegistration;
export type PostQuestionsMutationError = ErrorType<BadRequestResponse>;

/**
 * @summary 質問登録
 */
export const usePostQuestions = <TError = ErrorType<BadRequestResponse>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postQuestions>>,
    TError,
    {data: QuestionRegistration},
    TContext
  >;
}) => {
  const mutationOptions = getPostQuestionsMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 特定の質問および紐づく回答とコメントを取得します。
 * @summary 質問取得
 */
export const getDetailQuestion = (questionId: string, signal?: AbortSignal) => {
  return backendCustomInstance<QuestionAndAnswer>({url: `/questions/${questionId}`, method: 'get', signal});
};

export const getGetDetailQuestionQueryKey = (questionId: string) => [`/questions/${questionId}`] as const;

export const getGetDetailQuestionQueryOptions = <
  TData = Awaited<ReturnType<typeof getDetailQuestion>>,
  TError = ErrorType<unknown>,
>(
  questionId: string,
  options?: {query?: UseQueryOptions<Awaited<ReturnType<typeof getDetailQuestion>>, TError, TData>},
): UseQueryOptions<Awaited<ReturnType<typeof getDetailQuestion>>, TError, TData> & {queryKey: QueryKey} => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDetailQuestionQueryKey(questionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDetailQuestion>>> = ({signal}) =>
    getDetailQuestion(questionId, signal);

  return {queryKey, queryFn, enabled: !!questionId, ...queryOptions};
};

export type GetDetailQuestionQueryResult = NonNullable<Awaited<ReturnType<typeof getDetailQuestion>>>;
export type GetDetailQuestionQueryError = ErrorType<unknown>;

/**
 * @summary 質問取得
 */
export const useGetDetailQuestion = <
  TData = Awaited<ReturnType<typeof getDetailQuestion>>,
  TError = ErrorType<unknown>,
>(
  questionId: string,
  options?: {query?: UseQueryOptions<Awaited<ReturnType<typeof getDetailQuestion>>, TError, TData>},
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
  const queryOptions = getGetDetailQuestionQueryOptions(questionId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {queryKey: QueryKey};

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * 回答を登録します。
 * @summary 回答登録
 */
export const postQuestionsQuestionIdAnswers = (questionId: string, answerRegistration: AnswerRegistration) => {
  return backendCustomInstance<AnswerContent>({
    url: `/questions/${questionId}/answers`,
    method: 'post',
    headers: {'Content-Type': 'application/json'},
    data: answerRegistration,
  });
};

export const getPostQuestionsQuestionIdAnswersMutationOptions = <
  TError = ErrorType<BadRequestResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postQuestionsQuestionIdAnswers>>,
    TError,
    {questionId: string; data: AnswerRegistration},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postQuestionsQuestionIdAnswers>>,
  TError,
  {questionId: string; data: AnswerRegistration},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postQuestionsQuestionIdAnswers>>,
    {questionId: string; data: AnswerRegistration}
  > = props => {
    const {questionId, data} = props ?? {};

    return postQuestionsQuestionIdAnswers(questionId, data);
  };

  return {mutationFn, ...mutationOptions};
};

export type PostQuestionsQuestionIdAnswersMutationResult = NonNullable<
  Awaited<ReturnType<typeof postQuestionsQuestionIdAnswers>>
>;
export type PostQuestionsQuestionIdAnswersMutationBody = AnswerRegistration;
export type PostQuestionsQuestionIdAnswersMutationError = ErrorType<BadRequestResponse>;

/**
 * @summary 回答登録
 */
export const usePostQuestionsQuestionIdAnswers = <
  TError = ErrorType<BadRequestResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postQuestionsQuestionIdAnswers>>,
    TError,
    {questionId: string; data: AnswerRegistration},
    TContext
  >;
}) => {
  const mutationOptions = getPostQuestionsQuestionIdAnswersMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 質問に対するコメントを登録します。
 * @summary コメント登録（質問）
 */
export const postDetailComment = (questionId: string, commentRegistration: CommentRegistration) => {
  return backendCustomInstance<CommentContent>({
    url: `/questions/${questionId}/comments`,
    method: 'post',
    headers: {'Content-Type': 'application/json'},
    data: commentRegistration,
  });
};

export const getPostDetailCommentMutationOptions = <
  TError = ErrorType<BadRequestResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postDetailComment>>,
    TError,
    {questionId: string; data: CommentRegistration},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postDetailComment>>,
  TError,
  {questionId: string; data: CommentRegistration},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postDetailComment>>,
    {questionId: string; data: CommentRegistration}
  > = props => {
    const {questionId, data} = props ?? {};

    return postDetailComment(questionId, data);
  };

  return {mutationFn, ...mutationOptions};
};

export type PostDetailCommentMutationResult = NonNullable<Awaited<ReturnType<typeof postDetailComment>>>;
export type PostDetailCommentMutationBody = CommentRegistration;
export type PostDetailCommentMutationError = ErrorType<BadRequestResponse>;

/**
 * @summary コメント登録（質問）
 */
export const usePostDetailComment = <TError = ErrorType<BadRequestResponse>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postDetailComment>>,
    TError,
    {questionId: string; data: CommentRegistration},
    TContext
  >;
}) => {
  const mutationOptions = getPostDetailCommentMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * 回答に対するコメントを登録します。
 * @summary コメント登録（回答）
 */
export const postQuestionsQuestionIdAnswersAnswerIdComments = (
  questionId: string,
  answerId: string,
  commentRegistration: CommentRegistration,
) => {
  return backendCustomInstance<CommentContent>({
    url: `/questions/${questionId}/answers/${answerId}/comments`,
    method: 'post',
    headers: {'Content-Type': 'application/json'},
    data: commentRegistration,
  });
};

export const getPostQuestionsQuestionIdAnswersAnswerIdCommentsMutationOptions = <
  TError = ErrorType<BadRequestResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postQuestionsQuestionIdAnswersAnswerIdComments>>,
    TError,
    {questionId: string; answerId: string; data: CommentRegistration},
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postQuestionsQuestionIdAnswersAnswerIdComments>>,
  TError,
  {questionId: string; answerId: string; data: CommentRegistration},
  TContext
> => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postQuestionsQuestionIdAnswersAnswerIdComments>>,
    {questionId: string; answerId: string; data: CommentRegistration}
  > = props => {
    const {questionId, answerId, data} = props ?? {};

    return postQuestionsQuestionIdAnswersAnswerIdComments(questionId, answerId, data);
  };

  return {mutationFn, ...mutationOptions};
};

export type PostQuestionsQuestionIdAnswersAnswerIdCommentsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postQuestionsQuestionIdAnswersAnswerIdComments>>
>;
export type PostQuestionsQuestionIdAnswersAnswerIdCommentsMutationBody = CommentRegistration;
export type PostQuestionsQuestionIdAnswersAnswerIdCommentsMutationError = ErrorType<BadRequestResponse>;

/**
 * @summary コメント登録（回答）
 */
export const usePostQuestionsQuestionIdAnswersAnswerIdComments = <
  TError = ErrorType<BadRequestResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postQuestionsQuestionIdAnswersAnswerIdComments>>,
    TError,
    {questionId: string; answerId: string; data: CommentRegistration},
    TContext
  >;
}) => {
  const mutationOptions = getPostQuestionsQuestionIdAnswersAnswerIdCommentsMutationOptions(options);

  return useMutation(mutationOptions);
};
