CREATE TABLE CLIENT (
  CLIENT_ID SERIAL NOT NULL,
  CLIENT_NAME VARCHAR(128) NOT NULL,
  INDUSTRY_CODE CHAR(2) NOT NULL,
  PRIMARY KEY (CLIENT_ID)
);
COMMENT ON table CLIENT is '顧客';
COMMENT ON column CLIENT.CLIENT_ID is '顧客ID';
COMMENT ON column CLIENT.CLIENT_NAME is '顧客名';
COMMENT ON column CLIENT.INDUSTRY_CODE is '業種コード';

CREATE TABLE DOUBLE_SUBMISSION (
  TOKEN VARCHAR(36) NOT NULL,
  CREATED_AT TIMESTAMP,
  PRIMARY KEY (TOKEN)
);
COMMENT ON table DOUBLE_SUBMISSION is '二重サブミット管理';
COMMENT ON column DOUBLE_SUBMISSION.TOKEN is 'トークン';
COMMENT ON column DOUBLE_SUBMISSION.CREATED_AT is '作成日時';

CREATE TABLE INDUSTRY (
  INDUSTRY_CODE CHAR(2) NOT NULL,
  INDUSTRY_NAME VARCHAR(50),
  PRIMARY KEY (INDUSTRY_CODE)
);
COMMENT ON table INDUSTRY is '業種';
COMMENT ON column INDUSTRY.INDUSTRY_CODE is '業種コード';
COMMENT ON column INDUSTRY.INDUSTRY_NAME is '業種名';

CREATE TABLE PASSWORD_HISTORY (
  PASSWORD_HISTORY_ID BIGINT NOT NULL,
  USER_ID INTEGER,
  USER_PASSWORD VARCHAR(44) NOT NULL,
  PRIMARY KEY (PASSWORD_HISTORY_ID)
);
COMMENT ON table PASSWORD_HISTORY is 'パスワード変更履歴';
COMMENT ON column PASSWORD_HISTORY.PASSWORD_HISTORY_ID is 'パスワード履歴';
COMMENT ON column PASSWORD_HISTORY.USER_ID is 'ユーザID';
COMMENT ON column PASSWORD_HISTORY.USER_PASSWORD is 'パスワード';

CREATE TABLE PROJECT (
  PROJECT_ID SERIAL NOT NULL,
  PROJECT_NAME VARCHAR(128) NOT NULL,
  PROJECT_TYPE VARCHAR(128) NOT NULL,
  PROJECT_CLASS VARCHAR(128) NOT NULL,
  PROJECT_START_DATE DATE,
  PROJECT_END_DATE DATE,
  CLIENT_ID INTEGER,
  PROJECT_MANAGER VARCHAR(128),
  PROJECT_LEADER VARCHAR(128),
  USER_ID INTEGER,
  NOTE VARCHAR(512),
  SALES INTEGER,
  COST_OF_GOODS_SOLD INTEGER,
  SGA INTEGER,
  ALLOCATION_OF_CORP_EXPENSES INTEGER,
  VERSION BIGINT NOT NULL DEFAULT 1,
  PRIMARY KEY (PROJECT_ID)
);
COMMENT ON table PROJECT is 'プロジェクト';
COMMENT ON column PROJECT.PROJECT_ID is 'プロジェクトID';
COMMENT ON column PROJECT.PROJECT_NAME is 'プロジェクト名';
COMMENT ON column PROJECT.PROJECT_TYPE is 'プロジェクト種別';
COMMENT ON column PROJECT.PROJECT_CLASS is 'プロジェクト分類';
COMMENT ON column PROJECT.PROJECT_START_DATE is 'プロジェクト開始日付';
COMMENT ON column PROJECT.PROJECT_END_DATE is 'プロジェクト終了日付';
COMMENT ON column PROJECT.CLIENT_ID is '顧客ID';
COMMENT ON column PROJECT.PROJECT_MANAGER is 'プロジェクトマネージャー';
COMMENT ON column PROJECT.PROJECT_LEADER is 'プロジェクトリーダー';
COMMENT ON column PROJECT.USER_ID is 'ユーザID';
COMMENT ON column PROJECT.NOTE is '備考';
COMMENT ON column PROJECT.SALES is '売上高';
COMMENT ON column PROJECT.COST_OF_GOODS_SOLD is '売上原価';
COMMENT ON column PROJECT.SGA is '販管費';
COMMENT ON column PROJECT.ALLOCATION_OF_CORP_EXPENSES is '本社配賦';
COMMENT ON column PROJECT.VERSION is 'バージョン番号';

CREATE TABLE SYSTEM_ACCOUNT (
  USER_ID SERIAL NOT NULL,
  LOGIN_ID VARCHAR(20) NOT NULL,
  USER_PASSWORD VARCHAR(44) NOT NULL,
  USER_ID_LOCKED BOOL NOT NULL,
  PASSWORD_EXPIRATION_DATE DATE NOT NULL,
  FAILED_COUNT SMALLINT NOT NULL,
  EFFECTIVE_DATE_FROM DATE,
  EFFECTIVE_DATE_TO DATE,
  LAST_LOGIN_DATE_TIME TIMESTAMP(6),
  VERSION BIGINT NOT NULL DEFAULT 1,
  PRIMARY KEY (USER_ID)
);
COMMENT ON table SYSTEM_ACCOUNT is 'システムアカウント';
COMMENT ON column SYSTEM_ACCOUNT.USER_ID is 'ユーザID';
COMMENT ON column SYSTEM_ACCOUNT.LOGIN_ID is 'ログインID';
COMMENT ON column SYSTEM_ACCOUNT.USER_PASSWORD is 'パスワード';
COMMENT ON column SYSTEM_ACCOUNT.USER_ID_LOCKED is 'ユーザIDロック';
COMMENT ON column SYSTEM_ACCOUNT.PASSWORD_EXPIRATION_DATE is 'パスワード有効期限';
COMMENT ON column SYSTEM_ACCOUNT.FAILED_COUNT is '認証失敗回数';
COMMENT ON column SYSTEM_ACCOUNT.EFFECTIVE_DATE_FROM is '有効期限(FROM)';
COMMENT ON column SYSTEM_ACCOUNT.EFFECTIVE_DATE_TO is '有効期限(TO)';
COMMENT ON column SYSTEM_ACCOUNT.LAST_LOGIN_DATE_TIME is '最終ログイン日時';
COMMENT ON column SYSTEM_ACCOUNT.VERSION is 'バージョン番号';

CREATE TABLE USER_SESSION (
  SESSION_ID VARCHAR(100) NOT NULL,
  SESSION_OBJECT BYTEA,
  EXPIRATION_DATETIME TIMESTAMP NOT NULL,
  PRIMARY KEY (SESSION_ID)
);
COMMENT ON table USER_SESSION is 'ユーザセッション';
COMMENT ON column USER_SESSION.SESSION_ID is 'セッションID';
COMMENT ON column USER_SESSION.SESSION_OBJECT is 'セッションオブジェクト';
COMMENT ON column USER_SESSION.EXPIRATION_DATETIME is '有効期限';

CREATE TABLE USERS (
  USER_ID INTEGER NOT NULL,
  KANJI_NAME VARCHAR(128) NOT NULL,
  KANA_NAME VARCHAR(128) NOT NULL,
  PRIMARY KEY (USER_ID)
);
COMMENT ON table USERS is 'ユーザ';
COMMENT ON column USERS.USER_ID is 'ユーザID';
COMMENT ON column USERS.KANJI_NAME is '漢字氏名';
COMMENT ON column USERS.KANA_NAME is 'ふりがな';

ALTER TABLE SYSTEM_ACCOUNT ADD CONSTRAINT UQ_SYSTEM_ACCOUNT_LOGIN_ID UNIQUE
(
  LOGIN_ID
);

ALTER TABLE CLIENT
ADD
FOREIGN KEY (
  INDUSTRY_CODE
) REFERENCES INDUSTRY (
  INDUSTRY_CODE
);

ALTER TABLE PASSWORD_HISTORY
ADD
FOREIGN KEY (
  USER_ID
) REFERENCES SYSTEM_ACCOUNT (
  USER_ID
);

ALTER TABLE PROJECT
ADD
FOREIGN KEY (
  CLIENT_ID
) REFERENCES CLIENT (
  CLIENT_ID
);

ALTER TABLE PROJECT
ADD
FOREIGN KEY (
  USER_ID
) REFERENCES SYSTEM_ACCOUNT (
  USER_ID
);

ALTER TABLE USERS
ADD
FOREIGN KEY (
  USER_ID
) REFERENCES SYSTEM_ACCOUNT (
  USER_ID
);
