FIND_BY_PROJECT =
SELECT
    PROJECT.PROJECT_ID,
    PROJECT.PROJECT_NAME,
    PROJECT.PROJECT_TYPE,
    PROJECT.PROJECT_CLASS,
    PROJECT.PROJECT_START_DATE,
    PROJECT.PROJECT_END_DATE,
    PROJECT.CLIENT_ID,
    PROJECT.PROJECT_MANAGER,
    PROJECT.PROJECT_LEADER,
    PROJECT.USER_ID,
    PROJECT.NOTE,
    PROJECT.SALES,
    PROJECT.COST_OF_GOODS_SOLD,
    PROJECT.SGA,
    PROJECT.ALLOCATION_OF_CORP_EXPENSES,
    PROJECT.VERSION,
    CLIENT.CLIENT_NAME
FROM
    PROJECT INNER JOIN CLIENT ON PROJECT.CLIENT_ID = CLIENT.CLIENT_ID
WHERE
    PROJECT.PROJECT_ID = ?
    AND PROJECT.USER_ID = ?
