# wjdp/htmltest

# 実行方法
# docker run -v (pwd)/build:/test/mobile-app-crib-notes -v (pwd)/.htmltest.yaml:/test/.htmltest.yaml --rm wjdp/htmltest --conf .htmltest.yaml

# https://github.com/wjdp/htmltest#wrench-configuration
DirectoryPath: build
HTTPHeaders:
  # Range: bytes=0-0を受け取ると416（Invalid Range）を返してくるサイトがある。
  # https://github.com/wjdp/htmltest/issues/164
  #   - https://mdxjs.com/
  #   - https://formik.org/
  #   - https://rnfirebase.io/
  Range: bytes=0-
  Accept: '*/*'
  # User Agentを指定しないと403や404を返すサイトがある。
  # https://github.com/wjdp/htmltest/issues/150
  #   - https://marketplace.visualstudio.com/items
  #   - https://play.google.com/store/apps/details
  User-Agent: "bot/0.1"
# rel=alternativeに入るURLがドメイン名まで含んでいるので、追加したページがNot Foundエラーになってしまう
CheckLinks: false
# og:urlに入るURLがドメイン名まで含んでいるので、追加したページがNot Foundエラーになってしまう
CheckMeta: false
IgnoreDirectoryMissingTrailingSlash: true
IgnoreInternalEmptyHash: true
IgnoreInternalURLs:
  - '#!'
  # Redocで表示しているページはSPAなので生成されるHTMLにはidは出力されていない。
  # htmltestではstaticなチェックしかできず、hash does not existになってしまうので無視する。
  - /mobile-app-crib-notes/react-native/santoku/design/api-document#operation/get-accounts-me-terms
  - /mobile-app-crib-notes/react-native/santoku/design/api-document#operation/post-accounts-me-terms
  - /mobile-app-crib-notes/react-native/santoku/design/api-document#operation/get-terms
IgnoreURLs:
  - localhost:19002
  - http://localhost:9080/api/todos
  # 認証が必要なURLは無視
  - https://developer.apple.com/account/resources/identifiers/add/bundleId
  - https://developer.apple.com/account/resources/identifiers/list/bundleId
  - https://developer.apple.com/account/resources/profiles
  - https://developer.apple.com/account/resources/authkeys/list
  - https://developer.apple.com/account/resources/profiles
  # 404になってしまうので無視
  - https://play.google.com/store/apps/details\?id=host.exp.exponent
  - https://marketplace.visualstudio.com/items\?itemName=msjsdiag.vscode-react-native
  - https://marketplace.visualstudio.com/items\?itemName=msjsdiag.vscode-react-native
  - https://marketplace.visualstudio.com/items\?itemName=esbenp.prettier-vscode
  - https://marketplace.visualstudio.com/items\?itemName=dbaeumer.vscode-eslint
  - https://marketplace.visualstudio.com/items\?itemName=EditorConfig.EditorConfig
  - https://marketplace.visualstudio.com/items\?itemName=eamodio.gitlens
  - https://marketplace.visualstudio.com/items\?itemName=streetsidesoftware.code-spell-checker
  - https://marketplace.visualstudio.com/items\?itemName=christian-kohler.path-intellisense
  - https://marketplace.visualstudio.com/items\?itemName=naumovs.color-highlight
  - https://marketplace.visualstudio.com/items\?itemName=2gua.rainbow-brackets
  - https://marketplace.visualstudio.com/items\?itemName=yzhang.markdown-all-in-one
  - https://marketplace.visualstudio.com/items\?itemName=byCedric.vscode-expo
  # 403になってしまうので無視
  - https://blog.expo.dev/
# タイムアウトでビルドが失敗するので、外部リンクのエラーは警告とし手動で問題ないかを確認とする。
IgnoreExternalBrokenLinks: true
# タイムアウトでビルドが失敗すると困るので、余裕を持って長めに設定しておく。
ExternalTimeout: 60
