trigger: none

pr:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'example-app/SantokuApp'
    exclude:
      - 'example-app/SantokuApp/README.md'
  drafts: false

name: $(date:yyyyMMdd)$(rev:.rr)

extends:
  template: deploy.yml
  parameters:
    buildVariants:
      - name: 'santokuAppReleaseInHouse'
        laneName: 'release_in_house'
        buildType: 'releaseInHouse'
        androidAppPath: 'android/app/build/outputs/bundle/santokuAppReleaseInHouse/app-santokuApp-releaseInHouse.aab'
        iOSAppPath: 'ios/build/SantokuAppReleaseInHouse.ipa'
