parameters:
- name: environments
  type: object
  default:
    - name: 'stg'
      laneName: 'stg'
      androidAppPath: 'android/app/build/outputs/bundle/release/app-release.aab'
      iOSAppPath: 'ios/build/santoku-app-stg.ipa'

variables:
- group: android
- group: apple
- group: deployGate
- group: santokuAppStg
- name: appDir
  value: '$(System.DefaultWorkingDirectory)/example-app/SantokuApp'
- name: branchName
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
    value: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
    value: $[ replace(variables['System.PullRequest.SourceBranch'], 'refs/heads/', '') ]
- name: npmConfigCache
  value: '$(Pipeline.Workspace)/.npm'

stages:
- ${{ each environment in parameters.environments }}:
  - stage: Android_${{environment.name}}
    displayName: Android_${{environment.name}}
    dependsOn: []
    jobs:
    - job: build_${{environment.name}}
      displayName: 'build ${{environment.name}}'
      pool:
        # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md
        vmImage: macOS-12
      steps:
      - task: UseRubyVersion@0
        inputs:
          versionSpec: '3.1.3'
          addToPath: true
      - task: NodeTool@0
        displayName: 'Use Node.js 16.18.0'
        inputs:
          versionSpec: '16.18.0'
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '11'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
      - task: Cache@2
        displayName: Cache npm
        inputs:
          key: 'npm | "$(Agent.OS)" | $(appDir)/package-lock.json'
          restoreKeys: |
            npm | "$(Agent.OS)"
          path: $(npmConfigCache)
      - task: CmdLine@2
        displayName: 'npm ci --cache $(npmConfigCache)'
        inputs:
          script: 'npm ci --cache $(npmConfigCache)'
          workingDirectory: '$(appDir)'
      - task: DownloadSecureFile@1
        displayName: 'Download Keystore file for Staging'
        inputs:
          secureFile: $(android_ReleaseInHouseKeyStoreSecureFileName)
      - task: CopyFiles@2
        displayName: 'Copy Keystore file to: $(appDir)'
        inputs:
          SourceFolder: '$(Agent.TempDirectory)'
          Contents: $(android_ReleaseInHouseKeyStoreSecureFileName)
          TargetFolder: '$(appDir)'
      - task: DownloadSecureFile@1
        name: googleServicesJson${{environment.name}}
        displayName: 'Download google-services.json file for ${{environment.name}}'
        inputs:
          secureFile: $(${{environment.name}}_GoogleServicesJsonSecureFileName)
      - task: CopyFiles@2
        displayName: 'Copy google-services.json file to: $(appDir)'
        inputs:
          SourceFolder: '$(Agent.TempDirectory)'
          Contents: $(${{environment.name}}_GoogleServicesJsonSecureFileName)
          TargetFolder: '$(appDir)'
      - task: CmdLine@2
        displayName: 'Rename google-services.json'
        inputs:
          script: |
            /bin/mv $(${{environment.name}}_GoogleServicesJsonSecureFileName) google-services.json
          workingDirectory: '$(appDir)'
      - task: CmdLine@2
        displayName: 'Prebuild Android app for ${{environment.name}}'
        inputs:
          script: 'fastlane android prebuild_${{environment.laneName}}'
          workingDirectory: '$(appDir)'
      - task: CmdLine@2
        displayName: 'Add gradle.properties settings for ReleaseInHouse'
        inputs:
          script: |
            echo '# Keystore properties for ReleaseInHouse' >> gradle.properties
            echo 'SANTOKU_APP_UPLOAD_KEYSTORE_FILE=$(appDir)/$(android_ReleaseInHouseKeyStoreSecureFileName)' >> gradle.properties
            echo 'SANTOKU_APP_UPLOAD_KEYSTORE_PASSWORD=$(android_ReleaseInHouseKeyStorePassword)' >> gradle.properties
            echo 'SANTOKU_APP_UPLOAD_KEY_ALIAS=$(android_ReleaseInHouseKeyAlias)' >> gradle.properties
            echo 'SANTOKU_APP_UPLOAD_KEY_PASSWORD=$(android_ReleaseInHouseKeyPassword)' >> gradle.properties
          workingDirectory: '$(appDir)/android'
      - task: CmdLine@2
        displayName: 'Build Android app for ${{environment.name}}'
        inputs:
          script: 'fastlane android build_${{environment.laneName}}'
          workingDirectory: '$(appDir)'
      - task: CmdLine@2
        displayName: 'Upload app to DeployGate'
        inputs:
          script: |
            curl -X POST -H "Authorization: token $(deployGate_OrganizationApiKey)" "https://deploygate.com/api/users/$(deployGate_OrganizationName)/apps" -F "file=@${{environment.androidAppPath}}" -F "distribution_name=$(branchName)" -F "message=$(Build.Reason) triggered build by $(Build.BuildNumber)"
          workingDirectory: '$(appDir)'
      - task: PublishPipelineArtifact@1
        displayName: 'Publish Artifact'
        inputs:
          targetPath: '$(appDir)/android/app/build/outputs'
          artifactType: 'pipeline'
          artifactName: '${{environment.name}}.aab'
          parallel: true
        condition: succeeded()
- ${{ each environment in parameters.environments }}:
  - stage: iOS_${{environment.name}}
    displayName: iOS_${{environment.name}}
    dependsOn: []
    jobs:
    - job: build_${{environment.name}}
      displayName: 'build ${{environment.name}}'
      pool:
        # https://github.com/actions/virtual-environments/blob/main/images/macos/macos-12-Readme.md
        vmImage: macOS-12
      steps:
      - task: UseRubyVersion@0
        inputs:
          versionSpec: '3.1.3'
          addToPath: true
      - task: InstallAppleCertificate@2
        displayName: 'Install an Apple certificate for ${{environment.name}}'
        inputs:
          certSecureFile: $(apple_DevelopmentCertificateSecureFileName)
          certPwd: $(apple_DevelopmentCertificatePassword)
      - task: InstallAppleCertificate@2
        displayName: 'Install an Apple certificate for ${{environment.name}}'
        inputs:
          certSecureFile: $(apple_DistributionCertificateSecureFileName)
          certPwd: $(apple_DistributionCertificatePassword)
      - task: InstallAppleProvisioningProfile@1
        displayName: 'Install an Apple provisioning profile for ${{environment.name}}'
        inputs:
          provProfileSecureFile: $(${{environment.name}}_AppleDevelopmentProvisioningProfileSecureFileName)
      - task: InstallAppleProvisioningProfile@1
        displayName: 'Install an Apple provisioning profile for ${{environment.name}}'
        inputs:
          provProfileSecureFile: $(${{environment.name}}_AppleDistributionProvisioningProfileSecureFileName)
      - task: CmdLine@2
        displayName: 'Use Xcode 14.0.1'
        inputs:
          script: 'sudo xcode-select --switch /Applications/Xcode_14.0.1.app'
      - task: NodeTool@0
        displayName: 'Use Node.js 16.18.0'
        inputs:
          versionSpec: '16.18.0'
      - task: Cache@2
        displayName: Cache npm
        inputs:
          key: 'npm | "$(Agent.OS)" | $(appDir)/package-lock.json'
          restoreKeys: |
            npm | "$(Agent.OS)"
          path: $(npmConfigCache)
      - task: CmdLine@2
        displayName: 'npm ci --cache $(npmConfigCache)'
        inputs:
          script: 'npm ci --cache $(npmConfigCache)'
          workingDirectory: '$(appDir)'
      - task: CmdLine@2
        displayName: 'bundle install'
        inputs:
          script: 'bundle install'
          workingDirectory: '$(appDir)'
      - task: DownloadSecureFile@1
        displayName: 'Download GoogleServices-Info.plist file for ${{environment.name}}'
        inputs:
          secureFile: $(${{environment.name}}_GoogleServicesInfoPlistSecureFileName)
      - task: CopyFiles@2
        displayName: 'Copy GoogleService-Info.plist file to: $(appDir)'
        inputs:
          SourceFolder: '$(Agent.TempDirectory)'
          Contents: $(${{environment.name}}_GoogleServicesInfoPlistSecureFileName)
          TargetFolder: '$(appDir)'
      - task: CmdLine@2
        displayName: 'Rename GoogleService-Info.plist'
        inputs:
          script: |
            /bin/mv $(${{environment.name}}_GoogleServicesInfoPlistSecureFileName) GoogleService-Info.plist
          workingDirectory: '$(appDir)'
      - task: CmdLine@2
        displayName: 'Prebuild iOS app for ${{environment.name}}'
        inputs:
          script: 'fastlane ios prebuild_${{environment.laneName}}'
          workingDirectory: '$(appDir)'
      - task: CmdLine@2
        displayName: 'Build iOS app for ${{environment.name}}'
        inputs:
          script: 'fastlane ios build_${{environment.laneName}}'
          workingDirectory: '$(appDir)'
      - task: CmdLine@2
        displayName: 'Upload app to DeployGate'
        inputs:
          script: |
            curl -X POST -H "Authorization: token $(deployGate_OrganizationApiKey)" "https://deploygate.com/api/users/$(deployGate_OrganizationName)/apps" -F "file=@${{environment.iOSAppPath}}" -F "distribution_name=$(branchName)" -F "message=$(Build.Reason) triggered build by $(Build.BuildNumber)"
          workingDirectory: '$(appDir)'
      - task: PublishPipelineArtifact@1
        displayName: 'Publish Artifact'
        inputs:
          targetPath: '$(appDir)/ios/build'
          artifactType: 'pipeline'
          artifactName: '${{environment.name}}.ipa'
          parallel: true
        condition: succeeded()
