trigger: none

pr:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'example-app/SantokuApp'
    exclude:
      - 'example-app/SantokuApp/README.md'
  drafts: false

name: $(date:yyyyMMdd)$(rev:.rr)

extends:
  template: deploy.yaml
  parameters:
    buildVariants:
      - name: 'devSantokuAppReleaseInHouse'
        laneName: 'dev_release_in_house'
        buildType: 'releaseInHouse'
        androidAppPath: 'android/app/build/outputs/bundle/devSantokuAppReleaseInHouse/app-devSantokuApp-releaseInHouse.aab'
        iOSAppPath: 'ios/build/DevSantokuAppReleaseInHouse.ipa'
