/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp Sandbox REST API
 * SantokuApp Sandbox REST API
 * OpenAPI spec version: 1.0.0
 */
import {useQuery, useInfiniteQuery, useMutation} from 'react-query';
import type {
  UseQueryOptions,
  UseInfiniteQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  UseInfiniteQueryResult,
  QueryKey,
} from 'react-query';
import type {
  ListTodoResponse,
  BadRequestResponse,
  ListTodoParams,
  Todo,
  TodoRegistration,
  ListTodoInfiniteResponse,
  ListTodoByCursorParams,
  NotFoundResponse,
} from './model';
import {sandboxCustomInstance} from '../../backend/utils/customInstance';
import type {ErrorType} from '../../backend/utils/customInstance';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * List todo
 * @summary List todo
 */
export const listTodo = (params?: ListTodoParams, signal?: AbortSignal) => {
  return sandboxCustomInstance<ListTodoResponse>({url: `/todos`, method: 'get', params, signal});
};

export const getListTodoQueryKey = (params?: ListTodoParams) => [`/todos`, ...(params ? [params] : [])];

export type ListTodoQueryResult = NonNullable<Awaited<ReturnType<typeof listTodo>>>;
export type ListTodoQueryError = ErrorType<BadRequestResponse>;

export const useListTodo = <TData = Awaited<ReturnType<typeof listTodo>>, TError = ErrorType<BadRequestResponse>>(
  params?: ListTodoParams,
  options?: {query?: UseQueryOptions<Awaited<ReturnType<typeof listTodo>>, TError, TData>},
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTodoQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listTodo>>> = ({signal}) => listTodo(params, signal);

  const query = useQuery<Awaited<ReturnType<typeof listTodo>>, TError, TData>(
    queryKey,
    queryFn,
    queryOptions,
  ) as UseQueryResult<TData, TError> & {queryKey: QueryKey};

  query.queryKey = queryKey;

  return query;
};

/**
 * Create todo
 * @summary Create todo
 */
export const postTodo = (todoRegistration: TodoRegistration) => {
  return sandboxCustomInstance<Todo>({
    url: `/todos`,
    method: 'post',
    headers: {'Content-Type': 'application/json'},
    data: todoRegistration,
  });
};

export type PostTodoMutationResult = NonNullable<Awaited<ReturnType<typeof postTodo>>>;
export type PostTodoMutationBody = TodoRegistration;
export type PostTodoMutationError = ErrorType<BadRequestResponse>;

export const usePostTodo = <TError = ErrorType<BadRequestResponse>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postTodo>>, TError, {data: TodoRegistration}, TContext>;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postTodo>>, {data: TodoRegistration}> = props => {
    const {data} = props ?? {};

    return postTodo(data);
  };

  return useMutation<Awaited<ReturnType<typeof postTodo>>, TError, {data: TodoRegistration}, TContext>(
    mutationFn,
    mutationOptions,
  );
};

/**
 * List todo by cursor
 * @summary List todo by cursor
 */
export const listTodoByCursor = (params?: ListTodoByCursorParams) => {
  return sandboxCustomInstance<ListTodoInfiniteResponse>({url: `/todos/infinite`, method: 'get', params});
};

export const getListTodoByCursorQueryKey = (params?: ListTodoByCursorParams) => [
  `/todos/infinite`,
  ...(params ? [params] : []),
];

export type ListTodoByCursorInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof listTodoByCursor>>>;
export type ListTodoByCursorInfiniteQueryError = ErrorType<BadRequestResponse>;

export const useListTodoByCursorInfinite = <
  TData = Awaited<ReturnType<typeof listTodoByCursor>>,
  TError = ErrorType<BadRequestResponse>,
>(
  params?: ListTodoByCursorParams,
  options?: {query?: UseInfiniteQueryOptions<Awaited<ReturnType<typeof listTodoByCursor>>, TError, TData>},
): UseInfiniteQueryResult<TData, TError> & {queryKey: QueryKey} => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListTodoByCursorQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listTodoByCursor>>> = ({pageParam}) =>
    listTodoByCursor({cursor: pageParam, ...params});

  const query = useInfiniteQuery<Awaited<ReturnType<typeof listTodoByCursor>>, TError, TData>(
    queryKey,
    queryFn,
    queryOptions,
  ) as UseInfiniteQueryResult<TData, TError> & {queryKey: QueryKey};

  query.queryKey = queryKey;

  return query;
};

/**
 * Get todo
 * @summary Get todo
 */
export const getTodo = (todoId: number, signal?: AbortSignal) => {
  return sandboxCustomInstance<Todo>({url: `/todos/${todoId}`, method: 'get', signal});
};

export const getGetTodoQueryKey = (todoId: number) => [`/todos/${todoId}`];

export type GetTodoQueryResult = NonNullable<Awaited<ReturnType<typeof getTodo>>>;
export type GetTodoQueryError = ErrorType<NotFoundResponse>;

export const useGetTodo = <TData = Awaited<ReturnType<typeof getTodo>>, TError = ErrorType<NotFoundResponse>>(
  todoId: number,
  options?: {query?: UseQueryOptions<Awaited<ReturnType<typeof getTodo>>, TError, TData>},
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTodoQueryKey(todoId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodo>>> = ({signal}) => getTodo(todoId, signal);

  const query = useQuery<Awaited<ReturnType<typeof getTodo>>, TError, TData>(queryKey, queryFn, {
    enabled: !!todoId,
    ...queryOptions,
  }) as UseQueryResult<TData, TError> & {queryKey: QueryKey};

  query.queryKey = queryKey;

  return query;
};

/**
 * Update todo
 * @summary Update todo
 */
export const putTodo = (todoId: number, todoRegistration: TodoRegistration) => {
  return sandboxCustomInstance<Todo>({
    url: `/todos/${todoId}`,
    method: 'put',
    headers: {'Content-Type': 'application/json'},
    data: todoRegistration,
  });
};

export type PutTodoMutationResult = NonNullable<Awaited<ReturnType<typeof putTodo>>>;
export type PutTodoMutationBody = TodoRegistration;
export type PutTodoMutationError = ErrorType<BadRequestResponse | NotFoundResponse>;

export const usePutTodo = <TError = ErrorType<BadRequestResponse | NotFoundResponse>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putTodo>>,
    TError,
    {todoId: number; data: TodoRegistration},
    TContext
  >;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putTodo>>,
    {todoId: number; data: TodoRegistration}
  > = props => {
    const {todoId, data} = props ?? {};

    return putTodo(todoId, data);
  };

  return useMutation<Awaited<ReturnType<typeof putTodo>>, TError, {todoId: number; data: TodoRegistration}, TContext>(
    mutationFn,
    mutationOptions,
  );
};

/**
 * Delete todo
 * @summary Delete todo
 */
export const deleteTodo = (todoId: number) => {
  return sandboxCustomInstance<void>({url: `/todos/${todoId}`, method: 'delete'});
};

export type DeleteTodoMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTodo>>>;

export type DeleteTodoMutationError = ErrorType<NotFoundResponse>;

export const useDeleteTodo = <TError = ErrorType<NotFoundResponse>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteTodo>>, TError, {todoId: number}, TContext>;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTodo>>, {todoId: number}> = props => {
    const {todoId} = props ?? {};

    return deleteTodo(todoId);
  };

  return useMutation<Awaited<ReturnType<typeof deleteTodo>>, TError, {todoId: number}, TContext>(
    mutationFn,
    mutationOptions,
  );
};
