name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths:
      - docs/**
      - src/**
      - static/**
      - landing-page/**
      - .editorconfig
      - .eslintrc.js
      - .htmltest.yaml
      - .markdownlint.js
      - .prettierrc.js
      - .stylelintrc.js
      - .textlintrc.js
      - babel.config.js
      - docusaurus.config.js
      - package.json
      - package-lock.json
      - prh.yaml
      - README.md
      - tsconfig.json
      - .github/workflows/gh-pages.yaml
      - .github/workflows/gh-pages-deploy.yaml
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint:
    name: Lints
    runs-on: macos-10.15
    env:
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      # Cache '.npm' to speed up clean-install when package-lock.json is updated.
      # Loosened up the restore-keys a bit, as it doesn't have to match the contents of package-lock.json exactly.
      - name: Cache .npm
        id: cache-npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          # If cache is corrupted, increment prefixed number.
          key: 1-${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            1-${{ runner.os }}-npm-

      # If package-lock.json matches, node_modules will also match.
      # So, cache node_modules directly to skip install step.
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          # If cache is corrupted, increment prefixed number.
          key: 1-${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          npm clean-install 2>&1 | tee /dev/stderr | test $(grep --count -E '(Error:|gyp ERR!)') -le 0

      - name: Set up reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Lint (textlint)
        continue-on-error: true
        run: |
          npm run -s lint:text -- -f checkstyle | reviewdog -tee -fail-on-error -reporter=github-check -f=checkstyle -name="textlint (GitHub Pages)"

      - name: Lint (markdownlint)
        continue-on-error: true
        run: |
          npm run -s lint:md 2>&1 | sed -e 's/^/e:/' | reviewdog -tee -fail-on-error -reporter=github-check -efm="%t:%f:%l:%c %m" -efm="%t:%f:%l %m" -name="markdownlint (GitHub Pages)"

      - name: Lint (ESLint)
        continue-on-error: true
        run: |
          npm run -s lint:es -- -f eslint-formatter-rdjson | reviewdog -tee -fail-on-error -reporter=github-check -f=rdjson -name="ESLint (GitHub Pages)"

      - name: Lint (TypeScript)
        continue-on-error: true
        run: |
          npm run -s lint:tsc | reviewdog -tee -fail-on-error -reporter=github-check -f=tsc -name="TypeScript (GitHub Pages)"

      - name: Lint (stylelint)
        continue-on-error: true
        run: |
          npm run -s lint:css | reviewdog -tee -fail-on-error -reporter=github-check -f=stylelint -name="stylelint (GitHub Pages)"

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      # Cache '.npm' to speed up clean-install when package-lock.json is updated.
      # Loosened up the restore-keys a bit, as it doesn't have to match the contents of package-lock.json exactly.
      - name: Cache .npm
        id: cache-npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          # If cache is corrupted, increment prefixed number.
          key: 1-${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            1-${{ runner.os }}-npm-

      # If package-lock.json matches, node_modules will also match.
      # So, cache node_modules directly to skip install step.
      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          # If cache is corrupted, increment prefixed number.
          key: 1-${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm clean-install

      - name: Build documents
        run: npm run build

      - name: Save artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mobile-app-crib-notes
          path: ./build
          retention-days: 30
