/**
 * Generated by orval v6.10.2 🍺
 * Do not edit manually.
 * SantokuApp REST API
 * SantokuAppのREST API。
 * OpenAPI spec version: 1.0.0
 */
import {useQuery, useMutation} from 'react-query';
import type {
  UseQueryOptions,
  UseMutationOptions,
  QueryFunction,
  MutationFunction,
  UseQueryResult,
  QueryKey,
} from 'react-query';
import type {
  Account,
  BadRequestResponse,
  AccountRegistration,
  AccountLoginResponse,
  UnauthorizedResponse,
  AccountLogin,
  ForbiddenResponse,
  AvatarImage,
  UpdateDeviceToken,
  TermsOfServiceAgreementStatus,
  AccountDeletion,
  LikesResponse,
  LikedEventResponse,
  LikedQuestionResponse,
} from '.././model';
import {backendCustomInstance} from '../../utils/customInstance';
import type {ErrorType} from '../../utils/customInstance';

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

/**
 * アカウントを登録します。アカウントの登録には、ニックネームとパスワードが必要です。

 * @summary アカウントの登録
 */
export const postSignup = (accountRegistration: AccountRegistration) => {
  return backendCustomInstance<Account>({
    url: `/signup`,
    method: 'post',
    headers: {'Content-Type': 'application/json'},
    data: accountRegistration,
  });
};

export type PostSignupMutationResult = NonNullable<Awaited<ReturnType<typeof postSignup>>>;
export type PostSignupMutationBody = AccountRegistration;
export type PostSignupMutationError = ErrorType<BadRequestResponse>;

export const usePostSignup = <TError = ErrorType<BadRequestResponse>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postSignup>>, TError, {data: AccountRegistration}, TContext>;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postSignup>>, {data: AccountRegistration}> = props => {
    const {data} = props ?? {};

    return postSignup(data);
  };

  return useMutation<Awaited<ReturnType<typeof postSignup>>, TError, {data: AccountRegistration}, TContext>(
    mutationFn,
    mutationOptions,
  );
};
/**
 * アカウントIDとパスワードを指定してログインします。

 * @summary ログインする
 */
export const postLogin = (accountLogin: AccountLogin) => {
  return backendCustomInstance<AccountLoginResponse>({
    url: `/login`,
    method: 'post',
    headers: {'Content-Type': 'application/json'},
    data: accountLogin,
  });
};

export type PostLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postLogin>>>;
export type PostLoginMutationBody = AccountLogin;
export type PostLoginMutationError = ErrorType<BadRequestResponse | UnauthorizedResponse>;

export const usePostLogin = <
  TError = ErrorType<BadRequestResponse | UnauthorizedResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError, {data: AccountLogin}, TContext>;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLogin>>, {data: AccountLogin}> = props => {
    const {data} = props ?? {};

    return postLogin(data);
  };

  return useMutation<Awaited<ReturnType<typeof postLogin>>, TError, {data: AccountLogin}, TContext>(
    mutationFn,
    mutationOptions,
  );
};
/**
 * ログアウトします。
 * @summary ログアウトする
 */
export const postLogout = () => {
  return backendCustomInstance<void>({url: `/logout`, method: 'post'});
};

export type PostLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postLogout>>>;

export type PostLogoutMutationError = ErrorType<BadRequestResponse | ForbiddenResponse>;

export const usePostLogout = <
  TError = ErrorType<BadRequestResponse | ForbiddenResponse>,
  TVariables = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postLogout>>, TError, TVariables, TContext>;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLogout>>, TVariables> = () => {
    return postLogout();
  };

  return useMutation<Awaited<ReturnType<typeof postLogout>>, TError, TVariables, TContext>(mutationFn, mutationOptions);
};
/**
 * アカウントIDをキーとして登録されているアカウントを取得する。

 * @summary アカウントの取得
 */
export const getAccountsAccountId = (accountId: string, signal?: AbortSignal) => {
  return backendCustomInstance<Account>({url: `/accounts/${accountId}`, method: 'get', signal});
};

export const getGetAccountsAccountIdQueryKey = (accountId: string) => [`/accounts/${accountId}`];

export type GetAccountsAccountIdQueryResult = NonNullable<Awaited<ReturnType<typeof getAccountsAccountId>>>;
export type GetAccountsAccountIdQueryError = ErrorType<unknown>;

export const useGetAccountsAccountId = <
  TData = Awaited<ReturnType<typeof getAccountsAccountId>>,
  TError = ErrorType<unknown>,
>(
  accountId: string,
  options?: {query?: UseQueryOptions<Awaited<ReturnType<typeof getAccountsAccountId>>, TError, TData>},
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAccountsAccountIdQueryKey(accountId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccountsAccountId>>> = ({signal}) =>
    getAccountsAccountId(accountId, signal);

  const query = useQuery<Awaited<ReturnType<typeof getAccountsAccountId>>, TError, TData>(queryKey, queryFn, {
    enabled: !!accountId,
    ...queryOptions,
  }) as UseQueryResult<TData, TError> & {queryKey: QueryKey};

  query.queryKey = queryKey;

  return query;
};

/**
 * アバターを取得する。
サポートしているフォーマットは以下になります。
- png
- jpg
- jpeg
- bmp
- gif
- webp

 * @summary アバターを取得する
 */
export const getAccountsAccountIdAvatar = (accountId: string, signal?: AbortSignal) => {
  return backendCustomInstance<AvatarImage>({url: `/accounts/${accountId}/avatar`, method: 'get', signal});
};

export const getGetAccountsAccountIdAvatarQueryKey = (accountId: string) => [`/accounts/${accountId}/avatar`];

export type GetAccountsAccountIdAvatarQueryResult = NonNullable<Awaited<ReturnType<typeof getAccountsAccountIdAvatar>>>;
export type GetAccountsAccountIdAvatarQueryError = ErrorType<unknown>;

export const useGetAccountsAccountIdAvatar = <
  TData = Awaited<ReturnType<typeof getAccountsAccountIdAvatar>>,
  TError = ErrorType<unknown>,
>(
  accountId: string,
  options?: {query?: UseQueryOptions<Awaited<ReturnType<typeof getAccountsAccountIdAvatar>>, TError, TData>},
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAccountsAccountIdAvatarQueryKey(accountId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccountsAccountIdAvatar>>> = ({signal}) =>
    getAccountsAccountIdAvatar(accountId, signal);

  const query = useQuery<Awaited<ReturnType<typeof getAccountsAccountIdAvatar>>, TError, TData>(queryKey, queryFn, {
    enabled: !!accountId,
    ...queryOptions,
  }) as UseQueryResult<TData, TError> & {queryKey: QueryKey};

  query.queryKey = queryKey;

  return query;
};

/**
 * ログイン済みのアカウントを取得する。

 * @summary ログイン済みアカウントの取得
 */
export const getAccountsMe = (signal?: AbortSignal) => {
  return backendCustomInstance<Account>({url: `/accounts/me`, method: 'get', signal});
};

export const getGetAccountsMeQueryKey = () => [`/accounts/me`];

export type GetAccountsMeQueryResult = NonNullable<Awaited<ReturnType<typeof getAccountsMe>>>;
export type GetAccountsMeQueryError = ErrorType<ForbiddenResponse>;

export const useGetAccountsMe = <
  TData = Awaited<ReturnType<typeof getAccountsMe>>,
  TError = ErrorType<ForbiddenResponse>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getAccountsMe>>, TError, TData>;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAccountsMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccountsMe>>> = ({signal}) => getAccountsMe(signal);

  const query = useQuery<Awaited<ReturnType<typeof getAccountsMe>>, TError, TData>(
    queryKey,
    queryFn,
    queryOptions,
  ) as UseQueryResult<TData, TError> & {queryKey: QueryKey};

  query.queryKey = queryKey;

  return query;
};

/**
 * ログイン済みアカウントのアバターを取得する。
サポートしているフォーマットは以下になります。
- png
- jpg
- jpeg
- bmp
- gif
- webp

 * @summary ログイン済みアカウントのアバターを取得する
 */
export const getAccountsMeAvatar = (signal?: AbortSignal) => {
  return backendCustomInstance<AvatarImage>({url: `/accounts/me/avatar`, method: 'get', signal});
};

export const getGetAccountsMeAvatarQueryKey = () => [`/accounts/me/avatar`];

export type GetAccountsMeAvatarQueryResult = NonNullable<Awaited<ReturnType<typeof getAccountsMeAvatar>>>;
export type GetAccountsMeAvatarQueryError = ErrorType<unknown>;

export const useGetAccountsMeAvatar = <
  TData = Awaited<ReturnType<typeof getAccountsMeAvatar>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getAccountsMeAvatar>>, TError, TData>;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAccountsMeAvatarQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccountsMeAvatar>>> = ({signal}) =>
    getAccountsMeAvatar(signal);

  const query = useQuery<Awaited<ReturnType<typeof getAccountsMeAvatar>>, TError, TData>(
    queryKey,
    queryFn,
    queryOptions,
  ) as UseQueryResult<TData, TError> & {queryKey: QueryKey};

  query.queryKey = queryKey;

  return query;
};

/**
 * ログイン済みアカウントのアバターを登録する。

 * @summary ログイン済みアカウントのアバターを登録する
 */
export const putAccountsMeAvatar = (avatarImage: AvatarImage) => {
  const formData = new FormData();
  if (avatarImage.avatarImage !== undefined) {
    formData.append('avatarImage', avatarImage.avatarImage);
  }

  return backendCustomInstance<void>({
    url: `/accounts/me/avatar`,
    method: 'put',
    headers: {'Content-Type': 'multipart/form-data'},
    data: formData,
  });
};

export type PutAccountsMeAvatarMutationResult = NonNullable<Awaited<ReturnType<typeof putAccountsMeAvatar>>>;
export type PutAccountsMeAvatarMutationBody = AvatarImage;
export type PutAccountsMeAvatarMutationError = ErrorType<unknown>;

export const usePutAccountsMeAvatar = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof putAccountsMeAvatar>>, TError, {data: AvatarImage}, TContext>;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof putAccountsMeAvatar>>, {data: AvatarImage}> = props => {
    const {data} = props ?? {};

    return putAccountsMeAvatar(data);
  };

  return useMutation<Awaited<ReturnType<typeof putAccountsMeAvatar>>, TError, {data: AvatarImage}, TContext>(
    mutationFn,
    mutationOptions,
  );
};
/**
 * ログイン済みアカウントのデバイス登録トークンを更新する。

 * @summary ログイン済みアカウントのデバイス登録トークンの更新
 */
export const postAccountsMeDeviceToken = (updateDeviceToken: UpdateDeviceToken) => {
  return backendCustomInstance<void>({
    url: `/accounts/me/device-token`,
    method: 'post',
    headers: {'Content-Type': 'application/json'},
    data: updateDeviceToken,
  });
};

export type PostAccountsMeDeviceTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAccountsMeDeviceToken>>
>;
export type PostAccountsMeDeviceTokenMutationBody = UpdateDeviceToken;
export type PostAccountsMeDeviceTokenMutationError = ErrorType<unknown>;

export const usePostAccountsMeDeviceToken = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAccountsMeDeviceToken>>,
    TError,
    {data: UpdateDeviceToken},
    TContext
  >;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAccountsMeDeviceToken>>,
    {data: UpdateDeviceToken}
  > = props => {
    const {data} = props ?? {};

    return postAccountsMeDeviceToken(data);
  };

  return useMutation<
    Awaited<ReturnType<typeof postAccountsMeDeviceToken>>,
    TError,
    {data: UpdateDeviceToken},
    TContext
  >(mutationFn, mutationOptions);
};
/**
 * ログイン済みアカウントの有効な利用規約に同意しているかの状態を取得します。

 * @summary ログイン済みアカウントの利用規約同意状態確認
 */
export const getAccountsMeTerms = (signal?: AbortSignal) => {
  return backendCustomInstance<TermsOfServiceAgreementStatus>({url: `/accounts/me/terms`, method: 'get', signal});
};

export const getGetAccountsMeTermsQueryKey = () => [`/accounts/me/terms`];

export type GetAccountsMeTermsQueryResult = NonNullable<Awaited<ReturnType<typeof getAccountsMeTerms>>>;
export type GetAccountsMeTermsQueryError = ErrorType<unknown>;

export const useGetAccountsMeTerms = <
  TData = Awaited<ReturnType<typeof getAccountsMeTerms>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getAccountsMeTerms>>, TError, TData>;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAccountsMeTermsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccountsMeTerms>>> = ({signal}) =>
    getAccountsMeTerms(signal);

  const query = useQuery<Awaited<ReturnType<typeof getAccountsMeTerms>>, TError, TData>(
    queryKey,
    queryFn,
    queryOptions,
  ) as UseQueryResult<TData, TError> & {queryKey: QueryKey};

  query.queryKey = queryKey;

  return query;
};

/**
 * ログイン済みアカウントにおいて、指定された利用規約のバージョンに同意します。

 * @summary ログイン済みアカウントの利用規約同意
 */
export const postAccountsMeTerms = (termsOfServiceAgreementStatus: TermsOfServiceAgreementStatus) => {
  return backendCustomInstance<TermsOfServiceAgreementStatus>({
    url: `/accounts/me/terms`,
    method: 'post',
    headers: {'Content-Type': 'application/json'},
    data: termsOfServiceAgreementStatus,
  });
};

export type PostAccountsMeTermsMutationResult = NonNullable<Awaited<ReturnType<typeof postAccountsMeTerms>>>;
export type PostAccountsMeTermsMutationBody = TermsOfServiceAgreementStatus;
export type PostAccountsMeTermsMutationError = ErrorType<BadRequestResponse>;

export const usePostAccountsMeTerms = <TError = ErrorType<BadRequestResponse>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAccountsMeTerms>>,
    TError,
    {data: TermsOfServiceAgreementStatus},
    TContext
  >;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAccountsMeTerms>>,
    {data: TermsOfServiceAgreementStatus}
  > = props => {
    const {data} = props ?? {};

    return postAccountsMeTerms(data);
  };

  return useMutation<
    Awaited<ReturnType<typeof postAccountsMeTerms>>,
    TError,
    {data: TermsOfServiceAgreementStatus},
    TContext
  >(mutationFn, mutationOptions);
};
/**
 * ログイン済みアカウントを削除します。

アカウントの削除にパスワードを要求するので、DELETEメソッドではなくPOSTメソッドを利用しています。

参考: [4.3.5. DELETE - RFC 7231](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.5)

> A payload within a DELETE request message has no defined semantics;
> sending a payload body on a DELETE request might cause some existing
> implementations to reject the request.

 * @summary ログイン済みアカウント削除
 */
export const deleteAccountsMeDelete = (accountDeletion: AccountDeletion) => {
  return backendCustomInstance<void>({
    url: `/accounts/me/delete`,
    method: 'post',
    headers: {'Content-Type': 'application/json'},
    data: accountDeletion,
  });
};

export type DeleteAccountsMeDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteAccountsMeDelete>>>;
export type DeleteAccountsMeDeleteMutationBody = AccountDeletion;
export type DeleteAccountsMeDeleteMutationError = ErrorType<
  BadRequestResponse | UnauthorizedResponse | ForbiddenResponse
>;

export const useDeleteAccountsMeDelete = <
  TError = ErrorType<BadRequestResponse | UnauthorizedResponse | ForbiddenResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAccountsMeDelete>>,
    TError,
    {data: AccountDeletion},
    TContext
  >;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAccountsMeDelete>>,
    {data: AccountDeletion}
  > = props => {
    const {data} = props ?? {};

    return deleteAccountsMeDelete(data);
  };

  return useMutation<Awaited<ReturnType<typeof deleteAccountsMeDelete>>, TError, {data: AccountDeletion}, TContext>(
    mutationFn,
    mutationOptions,
  );
};
/**
 * いいね済のイベント、質問、回答、コメントを取得します。
 * @summary いいね済の取得
 */
export const getAccountsMeLikes = (signal?: AbortSignal) => {
  return backendCustomInstance<LikesResponse>({url: `/accounts/me/likes`, method: 'get', signal});
};

export const getGetAccountsMeLikesQueryKey = () => [`/accounts/me/likes`];

export type GetAccountsMeLikesQueryResult = NonNullable<Awaited<ReturnType<typeof getAccountsMeLikes>>>;
export type GetAccountsMeLikesQueryError = ErrorType<unknown>;

export const useGetAccountsMeLikes = <
  TData = Awaited<ReturnType<typeof getAccountsMeLikes>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getAccountsMeLikes>>, TError, TData>;
}): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAccountsMeLikesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccountsMeLikes>>> = ({signal}) =>
    getAccountsMeLikes(signal);

  const query = useQuery<Awaited<ReturnType<typeof getAccountsMeLikes>>, TError, TData>(
    queryKey,
    queryFn,
    queryOptions,
  ) as UseQueryResult<TData, TError> & {queryKey: QueryKey};

  query.queryKey = queryKey;

  return query;
};

/**
 * イベントに対するいいねを行います。
 * @summary いいねの実施（イベント）
 */
export const putEventsEventIdLike = (eventId: string) => {
  return backendCustomInstance<void>({url: `/accounts/me/likes/events/${eventId}`, method: 'put'});
};

export type PutEventsEventIdLikeMutationResult = NonNullable<Awaited<ReturnType<typeof putEventsEventIdLike>>>;

export type PutEventsEventIdLikeMutationError = ErrorType<unknown>;

export const usePutEventsEventIdLike = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof putEventsEventIdLike>>, TError, {eventId: string}, TContext>;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof putEventsEventIdLike>>, {eventId: string}> = props => {
    const {eventId} = props ?? {};

    return putEventsEventIdLike(eventId);
  };

  return useMutation<Awaited<ReturnType<typeof putEventsEventIdLike>>, TError, {eventId: string}, TContext>(
    mutationFn,
    mutationOptions,
  );
};
/**
 * イベントに対するいいねを取り消します。
 * @summary いいねの取消（イベント）
 */
export const deleteEventsEventIdLike = (eventId: string) => {
  return backendCustomInstance<void>({url: `/accounts/me/likes/events/${eventId}`, method: 'delete'});
};

export type DeleteEventsEventIdLikeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteEventsEventIdLike>>>;

export type DeleteEventsEventIdLikeMutationError = ErrorType<unknown>;

export const useDeleteEventsEventIdLike = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteEventsEventIdLike>>,
    TError,
    {eventId: string},
    TContext
  >;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteEventsEventIdLike>>,
    {eventId: string}
  > = props => {
    const {eventId} = props ?? {};

    return deleteEventsEventIdLike(eventId);
  };

  return useMutation<Awaited<ReturnType<typeof deleteEventsEventIdLike>>, TError, {eventId: string}, TContext>(
    mutationFn,
    mutationOptions,
  );
};
/**
 * 特定のイベントについていいね済のイベントを取得します。いいね済の場合はイベントIDが返ります。
 * @summary いいね済の取得（イベント）
 */
export const getAccountsMeLikesEventsEventId = (eventId: string, signal?: AbortSignal) => {
  return backendCustomInstance<LikedEventResponse>({
    url: `/accounts/me/likes/events/${eventId}`,
    method: 'get',
    signal,
  });
};

export const getGetAccountsMeLikesEventsEventIdQueryKey = (eventId: string) => [`/accounts/me/likes/events/${eventId}`];

export type GetAccountsMeLikesEventsEventIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccountsMeLikesEventsEventId>>
>;
export type GetAccountsMeLikesEventsEventIdQueryError = ErrorType<unknown>;

export const useGetAccountsMeLikesEventsEventId = <
  TData = Awaited<ReturnType<typeof getAccountsMeLikesEventsEventId>>,
  TError = ErrorType<unknown>,
>(
  eventId: string,
  options?: {query?: UseQueryOptions<Awaited<ReturnType<typeof getAccountsMeLikesEventsEventId>>, TError, TData>},
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAccountsMeLikesEventsEventIdQueryKey(eventId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccountsMeLikesEventsEventId>>> = ({signal}) =>
    getAccountsMeLikesEventsEventId(eventId, signal);

  const query = useQuery<Awaited<ReturnType<typeof getAccountsMeLikesEventsEventId>>, TError, TData>(
    queryKey,
    queryFn,
    {enabled: !!eventId, ...queryOptions},
  ) as UseQueryResult<TData, TError> & {queryKey: QueryKey};

  query.queryKey = queryKey;

  return query;
};

/**
 * 質問に対するいいねを行います。
 * @summary いいねの実施（質問）
 */
export const putQuestionsQuestionIdLike = (questionId: string) => {
  return backendCustomInstance<void>({url: `/accounts/me/likes/questions/${questionId}`, method: 'put'});
};

export type PutQuestionsQuestionIdLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof putQuestionsQuestionIdLike>>
>;

export type PutQuestionsQuestionIdLikeMutationError = ErrorType<unknown>;

export const usePutQuestionsQuestionIdLike = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putQuestionsQuestionIdLike>>,
    TError,
    {questionId: string},
    TContext
  >;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putQuestionsQuestionIdLike>>,
    {questionId: string}
  > = props => {
    const {questionId} = props ?? {};

    return putQuestionsQuestionIdLike(questionId);
  };

  return useMutation<Awaited<ReturnType<typeof putQuestionsQuestionIdLike>>, TError, {questionId: string}, TContext>(
    mutationFn,
    mutationOptions,
  );
};
/**
 * 質問に対するいいねを取り消します。
 * @summary いいねの取消（質問）
 */
export const deleteQuestionsQuestionIdLike = (questionId: string) => {
  return backendCustomInstance<void>({url: `/accounts/me/likes/questions/${questionId}`, method: 'delete'});
};

export type DeleteQuestionsQuestionIdLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteQuestionsQuestionIdLike>>
>;

export type DeleteQuestionsQuestionIdLikeMutationError = ErrorType<unknown>;

export const useDeleteQuestionsQuestionIdLike = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteQuestionsQuestionIdLike>>,
    TError,
    {questionId: string},
    TContext
  >;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteQuestionsQuestionIdLike>>,
    {questionId: string}
  > = props => {
    const {questionId} = props ?? {};

    return deleteQuestionsQuestionIdLike(questionId);
  };

  return useMutation<Awaited<ReturnType<typeof deleteQuestionsQuestionIdLike>>, TError, {questionId: string}, TContext>(
    mutationFn,
    mutationOptions,
  );
};
/**
 * 特定の質問についていいね済の質問および紐づく回答、コメントを取得します。いいね済の場合はIDが返ります。
 * @summary いいね済の取得（質問）
 */
export const getAccountsMeLikesQuestionsQuestionId = (questionId: string, signal?: AbortSignal) => {
  return backendCustomInstance<LikedQuestionResponse>({
    url: `/accounts/me/likes/questions/${questionId}`,
    method: 'get',
    signal,
  });
};

export const getGetAccountsMeLikesQuestionsQuestionIdQueryKey = (questionId: string) => [
  `/accounts/me/likes/questions/${questionId}`,
];

export type GetAccountsMeLikesQuestionsQuestionIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAccountsMeLikesQuestionsQuestionId>>
>;
export type GetAccountsMeLikesQuestionsQuestionIdQueryError = ErrorType<unknown>;

export const useGetAccountsMeLikesQuestionsQuestionId = <
  TData = Awaited<ReturnType<typeof getAccountsMeLikesQuestionsQuestionId>>,
  TError = ErrorType<unknown>,
>(
  questionId: string,
  options?: {query?: UseQueryOptions<Awaited<ReturnType<typeof getAccountsMeLikesQuestionsQuestionId>>, TError, TData>},
): UseQueryResult<TData, TError> & {queryKey: QueryKey} => {
  const {query: queryOptions} = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAccountsMeLikesQuestionsQuestionIdQueryKey(questionId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccountsMeLikesQuestionsQuestionId>>> = ({signal}) =>
    getAccountsMeLikesQuestionsQuestionId(questionId, signal);

  const query = useQuery<Awaited<ReturnType<typeof getAccountsMeLikesQuestionsQuestionId>>, TError, TData>(
    queryKey,
    queryFn,
    {enabled: !!questionId, ...queryOptions},
  ) as UseQueryResult<TData, TError> & {queryKey: QueryKey};

  query.queryKey = queryKey;

  return query;
};

/**
 * 質問のコメントに対するいいねを行います。
 * @summary いいねの実施（質問コメント）
 */
export const putQuestionsQuestionIdCommentCommentIdLike = (questionId: string, commentId: string) => {
  return backendCustomInstance<void>({
    url: `/accounts/me/likes/questions/${questionId}/comments/${commentId}`,
    method: 'put',
  });
};

export type PutQuestionsQuestionIdCommentCommentIdLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof putQuestionsQuestionIdCommentCommentIdLike>>
>;

export type PutQuestionsQuestionIdCommentCommentIdLikeMutationError = ErrorType<unknown>;

export const usePutQuestionsQuestionIdCommentCommentIdLike = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putQuestionsQuestionIdCommentCommentIdLike>>,
    TError,
    {questionId: string; commentId: string},
    TContext
  >;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putQuestionsQuestionIdCommentCommentIdLike>>,
    {questionId: string; commentId: string}
  > = props => {
    const {questionId, commentId} = props ?? {};

    return putQuestionsQuestionIdCommentCommentIdLike(questionId, commentId);
  };

  return useMutation<
    Awaited<ReturnType<typeof putQuestionsQuestionIdCommentCommentIdLike>>,
    TError,
    {questionId: string; commentId: string},
    TContext
  >(mutationFn, mutationOptions);
};
/**
 * 質問のコメントに対するいいねを取り消します。
 * @summary いいねの取消（質問コメント）
 */
export const deleteQuestionsQuestionIdCommentsCommentIdLike = (questionId: string, commentId: string) => {
  return backendCustomInstance<void>({
    url: `/accounts/me/likes/questions/${questionId}/comments/${commentId}`,
    method: 'delete',
  });
};

export type DeleteQuestionsQuestionIdCommentsCommentIdLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteQuestionsQuestionIdCommentsCommentIdLike>>
>;

export type DeleteQuestionsQuestionIdCommentsCommentIdLikeMutationError = ErrorType<unknown>;

export const useDeleteQuestionsQuestionIdCommentsCommentIdLike = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteQuestionsQuestionIdCommentsCommentIdLike>>,
    TError,
    {questionId: string; commentId: string},
    TContext
  >;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteQuestionsQuestionIdCommentsCommentIdLike>>,
    {questionId: string; commentId: string}
  > = props => {
    const {questionId, commentId} = props ?? {};

    return deleteQuestionsQuestionIdCommentsCommentIdLike(questionId, commentId);
  };

  return useMutation<
    Awaited<ReturnType<typeof deleteQuestionsQuestionIdCommentsCommentIdLike>>,
    TError,
    {questionId: string; commentId: string},
    TContext
  >(mutationFn, mutationOptions);
};
/**
 * 回答に対するいいねを行います。
 * @summary いいねの実施（回答）
 */
export const putQuestionsQuestionIdAnswerAnswerIdLike = (questionId: string, answerId: string) => {
  return backendCustomInstance<void>({
    url: `/accounts/me/likes/questions/${questionId}/answers/${answerId}`,
    method: 'put',
  });
};

export type PutQuestionsQuestionIdAnswerAnswerIdLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof putQuestionsQuestionIdAnswerAnswerIdLike>>
>;

export type PutQuestionsQuestionIdAnswerAnswerIdLikeMutationError = ErrorType<unknown>;

export const usePutQuestionsQuestionIdAnswerAnswerIdLike = <TError = ErrorType<unknown>, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putQuestionsQuestionIdAnswerAnswerIdLike>>,
    TError,
    {questionId: string; answerId: string},
    TContext
  >;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putQuestionsQuestionIdAnswerAnswerIdLike>>,
    {questionId: string; answerId: string}
  > = props => {
    const {questionId, answerId} = props ?? {};

    return putQuestionsQuestionIdAnswerAnswerIdLike(questionId, answerId);
  };

  return useMutation<
    Awaited<ReturnType<typeof putQuestionsQuestionIdAnswerAnswerIdLike>>,
    TError,
    {questionId: string; answerId: string},
    TContext
  >(mutationFn, mutationOptions);
};
/**
 * 回答に対するいいねを取り消します。
 * @summary いいねの取消（回答）
 */
export const deleteQuestionsQuestionIdAnswersAnswerIdLike = (questionId: string, answerId: string) => {
  return backendCustomInstance<void>({
    url: `/accounts/me/likes/questions/${questionId}/answers/${answerId}`,
    method: 'delete',
  });
};

export type DeleteQuestionsQuestionIdAnswersAnswerIdLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteQuestionsQuestionIdAnswersAnswerIdLike>>
>;

export type DeleteQuestionsQuestionIdAnswersAnswerIdLikeMutationError = ErrorType<unknown>;

export const useDeleteQuestionsQuestionIdAnswersAnswerIdLike = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteQuestionsQuestionIdAnswersAnswerIdLike>>,
    TError,
    {questionId: string; answerId: string},
    TContext
  >;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteQuestionsQuestionIdAnswersAnswerIdLike>>,
    {questionId: string; answerId: string}
  > = props => {
    const {questionId, answerId} = props ?? {};

    return deleteQuestionsQuestionIdAnswersAnswerIdLike(questionId, answerId);
  };

  return useMutation<
    Awaited<ReturnType<typeof deleteQuestionsQuestionIdAnswersAnswerIdLike>>,
    TError,
    {questionId: string; answerId: string},
    TContext
  >(mutationFn, mutationOptions);
};
/**
 * 回答のコメントに対するいいねを行います。
 * @summary いいねの実施（回答コメント）
 */
export const putQuestionsQuestionIdAnswerAnswerIdCommentCommentIdLike = (
  questionId: string,
  answerId: string,
  commentId: string,
) => {
  return backendCustomInstance<void>({
    url: `/accounts/me/likes/questions/${questionId}/answers/${answerId}/comments/${commentId}`,
    method: 'put',
  });
};

export type PutQuestionsQuestionIdAnswerAnswerIdCommentCommentIdLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof putQuestionsQuestionIdAnswerAnswerIdCommentCommentIdLike>>
>;

export type PutQuestionsQuestionIdAnswerAnswerIdCommentCommentIdLikeMutationError = ErrorType<unknown>;

export const usePutQuestionsQuestionIdAnswerAnswerIdCommentCommentIdLike = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putQuestionsQuestionIdAnswerAnswerIdCommentCommentIdLike>>,
    TError,
    {questionId: string; answerId: string; commentId: string},
    TContext
  >;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putQuestionsQuestionIdAnswerAnswerIdCommentCommentIdLike>>,
    {questionId: string; answerId: string; commentId: string}
  > = props => {
    const {questionId, answerId, commentId} = props ?? {};

    return putQuestionsQuestionIdAnswerAnswerIdCommentCommentIdLike(questionId, answerId, commentId);
  };

  return useMutation<
    Awaited<ReturnType<typeof putQuestionsQuestionIdAnswerAnswerIdCommentCommentIdLike>>,
    TError,
    {questionId: string; answerId: string; commentId: string},
    TContext
  >(mutationFn, mutationOptions);
};
/**
 * 回答のコメントに対するいいねを取り消します。
 * @summary いいねの取消（回答コメント）
 */
export const deleteQuestionsQuestionIdAnswersAnswerIdCommentsCommentIdLike = (
  questionId: string,
  answerId: string,
  commentId: string,
) => {
  return backendCustomInstance<void>({
    url: `/accounts/me/likes/questions/${questionId}/answers/${answerId}/comments/${commentId}`,
    method: 'delete',
  });
};

export type DeleteQuestionsQuestionIdAnswersAnswerIdCommentsCommentIdLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteQuestionsQuestionIdAnswersAnswerIdCommentsCommentIdLike>>
>;

export type DeleteQuestionsQuestionIdAnswersAnswerIdCommentsCommentIdLikeMutationError = ErrorType<unknown>;

export const useDeleteQuestionsQuestionIdAnswersAnswerIdCommentsCommentIdLike = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteQuestionsQuestionIdAnswersAnswerIdCommentsCommentIdLike>>,
    TError,
    {questionId: string; answerId: string; commentId: string},
    TContext
  >;
}) => {
  const {mutation: mutationOptions} = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteQuestionsQuestionIdAnswersAnswerIdCommentsCommentIdLike>>,
    {questionId: string; answerId: string; commentId: string}
  > = props => {
    const {questionId, answerId, commentId} = props ?? {};

    return deleteQuestionsQuestionIdAnswersAnswerIdCommentsCommentIdLike(questionId, answerId, commentId);
  };

  return useMutation<
    Awaited<ReturnType<typeof deleteQuestionsQuestionIdAnswersAnswerIdCommentsCommentIdLike>>,
    TError,
    {questionId: string; answerId: string; commentId: string},
    TContext
  >(mutationFn, mutationOptions);
};
